// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl_-7m_v0wvMSNgDv8yqttp2VlbDtZV50',
    appId: '1:308621376439:web:f4058494a960731354c632',
    messagingSenderId: '308621376439',
    projectId: 'budgex-ed4be',
    authDomain: 'budgex-ed4be.firebaseapp.com',
    storageBucket: 'budgex-ed4be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VwUg8q08Y93xwga8vNbaU-r1a__rNBM',
    appId: '1:308621376439:android:1f7f4e67201bfab254c632',
    messagingSenderId: '308621376439',
    projectId: 'budgex-ed4be',
    storageBucket: 'budgex-ed4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm_ESQzEnx9baxGjeRlH2azaSRypaWitU',
    appId: '1:308621376439:ios:8b91f46fd32fd3e954c632',
    messagingSenderId: '308621376439',
    projectId: 'budgex-ed4be',
    storageBucket: 'budgex-ed4be.appspot.com',
    iosBundleId: 'com.example.budgex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm_ESQzEnx9baxGjeRlH2azaSRypaWitU',
    appId: '1:308621376439:ios:de0315768cf42cf454c632',
    messagingSenderId: '308621376439',
    projectId: 'budgex-ed4be',
    storageBucket: 'budgex-ed4be.appspot.com',
    iosBundleId: 'com.example.budgex.RunnerTests',
  );
}
